[versions]
retrofit = "2.9.0"
okhttp = "4.9.2"
moshi = "1.12.0"
coil = "2.1.0"
apache-poi = "5.2.3"
truth = "1.4.2"
kotlinx-coroutines-test = "1.8.1"
androidx-test-ext-junit = "1.2.1"
androidx-test-core = "1.6.1"
androidx-test-runner = "1.6.1"
androidx-test-espresso-core = "3.6.1"

[libraries]
truth = { module = "com.google.truth:truth", version.ref = "truth" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext-junit" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test-core" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test-runner" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso-core" }
